language: go

go:
  - "1.11"

addons:
  postgresql: "9.5"

env:
  - TEST_DB_NAME=starttls_test

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get -t ./...

before_script:
  - psql -c 'CREATE DATABASE starttls_test;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
  - psql starttls_test < db/scripts/init_tables.sql

script:
  - golint -set_exit_status ./...
  - go test -race -coverprofile=profile.cov -covermode=atomic -v ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
