language: go

go:
  - "1.11"

addons:
  postgresql: "9.6"

env:
  - TEST_DB_NAME=starttls_test GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

before_script:
  - psql -c 'CREATE DATABASE starttls_test;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
  - psql starttls_test < db/scripts/init_tables.sql
    # Repeat the previous command to test idempotence of init_tables script
  - psql starttls_test < db/scripts/init_tables.sql

script:
  - golint -set_exit_status ./...
  - go test -race -coverprofile=profile.cov -covermode=atomic -v ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
