language: go

go:
  - "1.8"

services:
  - postgresql

env:
  - TEST_DB_NAME=starttls_test TEST_DB_PASSWORD=

install:
  - go get -u github.com/golang/lint/golint
  - go get ./...

before_script:
  - psql -c 'create database starttls_test;' -U postgres
  - psql starttls_test < db/scripts/init_tables.sql

script:
  - golint -set_exit_status ./...
  - go test -v .
  - go test -v ./policy
