language: go

go:
  - "1.11"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

env:
  - TEST_DB_NAME=starttls_test

before_install:
  - sudo -u postgres psql -c 'CREATE DATABASE starttls_test;'
  - sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - sudo -u postgres psql starttls_test -p 5433 < db/scripts/init_tables.sql

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get -t ./...

script:
  - golint -set_exit_status ./...
  - go test -race -coverprofile=profile.cov -covermode=atomic -v ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
