version: '2'
services:
    postgres:
        build: db/
        env_file:
          - .env
        environment:
          POSTGRES_DB: $DB_NAME
          POSTGRES_USER: $DB_USERNAME
          POSTGRES_PASSWORD: $DB_PASSWORD
    postgres_test:
        build: db/
        env_file:
          - .env.test
        environment:
          POSTGRES_DB: starttls_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    app:
        build: .
        volumes:
          - .:/go/src/github.com/EFForg/starttls-backend
        ports:
          - 8080:8080
        depends_on:
          - postgres
          - postgres_test
        env_file:
          - .env
