version: '2'
services:
    postgres:
        build: db/
        env_file:
          - .env
        environment:
          POSTGRES_DB: $DB_NAME
          POSTGRES_USER: $DB_USERNAME
          POSTGRES_PASSWORD: $DB_PASSWORD
        ports:
          - "5432:5432"
    app:
        build: .
        volumes:
          - .:/go/src/starttls-scanner
        ports:
          - 8080:8080
        depends_on:
          - postgres
        links:
          - postgres
        env_file:
          - .env
